<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.cache.interceptor.CacheErrorHandlerTests" tests="9" skipped="0" failures="0" errors="0" timestamp="2016-11-10T07:38:40" hostname="XB-20161010YVDY" time="0.463">
  <properties/>
  <testcase name="clearFail" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.145"/>
  <testcase name="evictFail" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.037"/>
  <testcase name="getFailProperException" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.036"/>
  <testcase name="putFail" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.041"/>
  <testcase name="getFail" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.035"/>
  <testcase name="getAndPutFail" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.043"/>
  <testcase name="putFailProperException" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.049"/>
  <testcase name="evictFailProperException" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.04"/>
  <testcase name="clearFailProperException" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.036"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
